### ISSUE TITLE
Hotkey is only captured on meet.google.com

### ISSUE THREAD

**Issue by tpott** [BashVideo/google-meet-push-to-talk#6]
One of the nice features of having a standalone voice chat application is that they have a system-wide push-to-talk button. Since this extension works within the browser, I think it would be a great addition if it was able to capture hotkeys from _any_ tab. 

This would make the logic for handling keyPresses more complicated (I'm guessing we'd have to use the [tabs](https://developer.chrome.com/extensions/tabs) API to capture in all tabs and `sendMessage` to the currently active tab). But I think it would be a big improvement!

**Comment by stopdropandrew** [comment]
Hi, I commented with a similar response in #7, but I'm not comfortable adding permission to access other tabs. If you can come up with a solution that doesn't require additional permissions I'd be happy to check it out!

If you are really set on it, feel free to fork and release a version with added permissions. Alternatively, you could look at a system-wide solution like https://github.com/yulrizka/osx-push-to-talk.
